# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 42a9cab18e33061b191074fa00e39b4333970c7851b0db270b5321e79f5c39d5b23e06ee6d156c6057b6a45312328edcf3c65c4af197f1c9a0d2bbd08c1daf2a

test:
  secret_key_base: 63c34c0484c35746363ac6b0f0bc30eb120987d628feeb6d5691b65384bad027f0dc26cda5b53e8de0750397c2eae519fbead8f586a0d3d3267692c67975c6c3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
